# Generated by Django 5.1.4 on 2025-09-15 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dairy', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='diaryentry',
            old_name='ai_reply',
            new_name='emotion_analysis',
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='suggestions',
            field=models.TextField(default='not detected'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='diaryentry',
            name='supportive_reply',
            field=models.TextField(default='unknown'),
            preserve_default=False,
        ),
    ]
